name: 'Argus Paul '
favicon: null
layout_spectrum: 0.50183
typography_spectrum: 0.88757
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0a0a0a'
    - '#404040'
    - '#fbfbfb'
    - '#a0a0a0'
    - '#7c7c7c'
  brandStrength: 0.4855645408388227
  lightness: 0.6824273990932852
  saturation: 0.9745348449796438
  rhythmicContrast: 0.8332665269263089
purpose: []
