name: 'Argus Paul '
favicon: null
layout_spectrum: 0.5905875097960234
typography_spectrum: 0.8199309450574219
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.4855645408388227
  lightness: 0.6824273990932852
  saturation: 0.9745348449796438
  rhythmicContrast: 0.8332665269263089
purpose: []
